import { Component, OnInit, ViewChild } from '@angular/core';
import { NavController } from '@ionic/angular';

@Component({
  selector: 'app-monitorias-list',
  templateUrl: './monitorias-list.component.html',
  styleUrls: ['./monitorias-list.component.scss'],
})
export class MonitoriasListComponent implements OnInit {

  public monitoriasInfo;
  public monitoriasEletro; 

  constructor(public navCtrl: NavController) {
    this.monitoriasInfo = [
      {nome:'Lingua Portuguesa e literatura Brasileira 1', id: 1},
      {nome:'Matemática 1', id: 2},
      {nome:'Física 1', id: 3},
      {nome:'Educação Física 1', id: 4},
      {nome:'Ling. Estrang.Moderna Inglês 1', id: 5},
      {nome:'Geografia 1', id: 6},
      {nome:'Filosofia 1', id: 7},
      {nome:'Sociologia 1', id: 8},
      {nome:'Informática Aplicada', id: 9},
      {nome:'Desenvolvimento web 1', id: 10},
      {nome:'Algoritmos 1', id: 11},
      {nome:'Instalação e Manutenção de Computadores 1', id: 12},
      {nome:'Lingua Portuguesa e literatura Brasileira 2', id: 13},
      {nome:'Matemática 2', id: 14},
      {nome:'Física 2', id: 15},
      {nome:'Educação Física 2', id: 16},
      {nome:'Ling. Estrang.Moderna Inglês 2', id: 17},
      {nome:'Geografia 2', id: 18},
      {nome:'Filosofia 2', id: 19},
      {nome:'Sociologia 2', id: 20},
      {nome:'Biologia 1', id: 21},
      {nome:'Quimica 1', id: 22},
      {nome:'Desenvolvimento web 2', id: 23},
      {nome:'Algoritmos 2', id: 24},
      {nome:'Instalação e Manutenção de Computadores 2', id: 25},
      {nome:'Lingua Portuguesa e literatura Brasileira 3', id: 26},
      {nome:'Matemática 3', id: 27},
      {nome:'Física 3', id: 28},
      {nome:'Educação Física 3', id: 29},
      {nome:'Ling. Estrang.Moderna Inglês 3', id: 30},
      {nome:'Geografia 3', id: 31},
      {nome:'Filosofia 3', id: 32},
      {nome:'Sociologia 3', id: 33},
      {nome:'Biologia 2', id: 34},
      {nome:'Quimica 2', id: 35},
      {nome:'Desenvolvimento web 3', id: 36},
      {nome:'Arte 1', id: 37},
      {nome:'História 1', id: 38},
      {nome:'Banco de Dados 1', id: 39},
      {nome:'Sistemas Operacionais 1', id: 40},
      {nome:'Lingua Portuguesa e literatura Brasileira 4', id: 41},
      {nome:'Matemática 4', id: 42},
      {nome:'Física 4', id: 43},
      {nome:'Educação Física 4', id: 44},
      {nome:'Ling. Estrang.Moderna Inglês 4', id: 45},
      {nome:'Geografia 4', id: 46},
      {nome:'Filosofia 4', id: 47},
      {nome:'Sociologia 4', id: 48},
      {nome:'Biologia 3', id: 49},
      {nome:'Quimica 3', id: 50},
      {nome:'Desenvolvimento web 4', id: 51},
      {nome:'Arte 2', id: 52},
      {nome:'História 2', id: 53},
      {nome:'Banco de Dados 2', id: 54},
      {nome:'Sistemas Operacionais 2', id: 55},
      {nome:'Lingua Portuguesa e literatura Brasileira 5', id: 56},
      {nome:'Matemática 5', id: 57},
      {nome:'Física 5', id: 58},
      {nome:'Educação Física 5', id: 59},
      {nome:'Programação para Dispositivos Moveis 1', id: 60},
      {nome:'Redes de Computadores 1', id: 61},
      {nome:'Empreendedorismo e inovação 1', id: 62},
      {nome:'Frameworks', id: 63},
      {nome:'Biologia 4', id: 64},
      {nome:'Quimica 4', id: 65},
      {nome:'História 3', id: 66},
      {nome:'Metodologia de Pesquisa', id: 67},
      {nome:'Lingua Portuguesa e literatura Brasileira 6', id: 68},
      {nome:'Matemática 6', id: 69},
      {nome:'Física 6', id: 70},
      {nome:'Tópicos Especiais em Tecnologia da Informação', id: 71},
      {nome:'Programação para Dispositivos Moveis 2', id: 72},
      {nome:'Redes de Computadores 2', id: 73},
      {nome:'Empreendedorismo e inovação 2', id: 74},
      {nome:'Gerenciamento e configuração de Serviços de Internet', id: 75},
      {nome:'Produção Técnica e Cientifica', id: 76},
      {nome:'Comunicação Técnica', id: 77},
      {nome:'História 4', id: 78},
      {nome:'Computador, Ética e Sociedade', id: 79},
    ]

    this.monitoriasEletro = [
      {nome:'Lingua Portuguesa e literatura Brasileira 1', id: 80},
      {nome:'Matemática 1', id: 81},
      {nome:'Física 1', id: 82},
      {nome:'Educação Física 1', id: 83},
      {nome:'Ling. Estrang.Moderna Inglês 1', id: 84},
      {nome:'Geografia 1', id: 85},
      {nome:'Filosofia 1', id: 86},
      {nome:'Sociologia 1', id: 87},
      {nome:'Eletricidade CC', id: 88},
      {nome:'Desenho Técnico e CAD', id: 89},
      {nome:'Informática Aplicada', id: 90},
      {nome:'Lingua Portuguesa e literatura Brasileira 2', id: 91},
      {nome:'Matemática 2', id: 92},
      {nome:'Física 2', id: 93},
      {nome:'Educação Física 2', id: 94},
      {nome:'Ling. Estrang.Moderna Inglês 2', id: 95},
      {nome:'Geografia 2', id: 96},
      {nome:'Filosofia 2', id: 97},
      {nome:'Sociologia 2', id: 98},
      {nome:'Biologia 1', id: 99},
      {nome:'Quimica 1', id: 100},
      {nome:'Eletricidade CA', id: 101},
      {nome:'Instalações Elétricas Prediais', id: 102},
      {nome:'Lingua Portuguesa e literatura Brasileira 3', id: 103},
      {nome:'Matemática 3', id: 104},
      {nome:'Física 3', id: 105},
      {nome:'	Educação Física 3', id: 106},
      {nome:'Ling. Estrang.Moderna Inglês 3', id: 107},
      {nome:'Geografia 3', id: 108},
      {nome:'Filosofia 3', id: 109},
      {nome:'Sociologia 3', id: 110},
      {nome:'Biologia 2', id: 111},
      {nome:'Quimica 2', id: 112},
      {nome:'História 1', id: 113},
      {nome:'Arte 1', id: 114},
      {nome:'Eletrônica Geral 1', id: 115},
      {nome:'Conversão de Energia', id: 116},
      {nome:'Eletrônica Digital', id: 117},
      {nome:'Redação e Metodologias Científicas', id: 118},
      {nome:'Lingua Portuguesa e literatura Brasileira 4', id: 119},
      {nome:'Matemática 4', id: 120},
      {nome:'Física 4', id: 121},
      {nome:'Educação Física 4', id: 122},
      {nome:'Ling. Estrang.Moderna Inglês 4', id: 123},
      {nome:'Geografia 4', id: 124},
      {nome:'Filosofia 4', id: 125},
      {nome:'Sociologia 4', id: 126},
      {nome:'Biologia 3', id: 127},
      {nome:'Quimica 3', id: 128},
      {nome:'História 2', id: 129},
      {nome:'Arte 2', id: 130},
      {nome:'Eletrônica Geral 2', id: 131},
      {nome:'Máquinas Elétricas e Acionamentos 1', id: 132},
      {nome:'Lingua Portuguesa e literatura Brasileira 5', id: 133},
      {nome:'Matemática 5', id: 134},
      {nome:'Física 5', id: 135},
      {nome:'Educação Física 5', id: 136},
      {nome:'Biologia 4', id: 137},
      {nome:'Quimica 4', id: 138},
      {nome:'História 3', id: 139},
      {nome:'Comandos Elétricos', id: 140},
      {nome:'Máquinas Elétricas e Acionamentos 2', id: 141},
      {nome:'Elétronica de Potência', id: 142},
      {nome:'Sistemas Microcontrolados', id: 143},
      {nome:'Pneumática e Hidráulica', id: 144},
      {nome:'Empreendedorismo e inovação', id: 145},
      {nome:'Lingua Portuguesa e literatura Brasileira 6', id: 146},
      {nome:'Matemática 6', id: 147},
      {nome:'Física 6', id: 148},
      {nome:'História 4', id: 149},
      {nome:'Instalações Elétricas Industriais', id: 150},
      {nome:'Geração, Transmissão e Distribuição Elétrica', id: 151},
      {nome:'Instrumentação e Controle', id: 152},
      {nome:'Acionamentos Especiais', id: 153},
      {nome:'Acionamento  Eletropneumático e Eletrohidráulico', id: 154},
      {nome:'Automação Industrial', id: 155},
      {nome:'Estátistica', id: 156},
      {nome:'Segurança do Trabalho', id: 157},
      {nome:'Meio Ambiente e Energias Renováveis', id: 158},
    ]
  }

  ngOnInit() {
  }


}